import type { Metadata } from "next";
import { Inter, League_Spartan, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins",
  subsets: ["latin"],
});

const leagueSpartan = League_Spartan({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--spartan",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Verdant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
